
spring.datasource.url=jdbc:mySql://localhost:3306/student_java_db
spring.datasource.username=Mankind
spring.datasource.password=Ptwamy0706!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
