spring.application.name=crudOperations

spring.datasource.url=jdbc:mysql://localhost:3306/student_java_db
spring.datasource.username=Mankind
spring.datasource.password=Ptwamy0706!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
