spring.application.name=firstWebProject
spring.datasource.url= jdbc:mysql://localhost:3306/login_java_db
spring.datasource.username=Mankind
spring.datasource.password=Ptwamy0706!

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.thymeleaf.cache = false

